### PR TITLE
standardizing to other SqlAlchemy coding conventions

### PR DESCRIPTION
**Pull request by jvanasco**
* migrated `black` config to `pyproject.toml`
* updated black version
* updated README to showcase code-of-conduct and development links

### CODE REVIEW

**Comment by jvanasco** [comment]
this PR did fail locally on:

>  sqlalchemy_collectd/server/tests/test_listener.py::ListenerTest::test_receive_resilency FAILED                                                     [ 43%]

I am not familiar enough with the library to address that.

**Comment by zzzeek** [comment]
wonder why it failed.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get revision cebf8ca81c6868785c52aa91651f16d25db6e5b8 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change cebf8ca81c6868785c52aa91651f16d25db6e5b8: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy-collectd/+/1697

**Comment by zzzeek** [comment]
I love F841

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

View this in Gerrit at https://gerrit.sqlalchemy.org/1697

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1697 has been **merged**. Congratulations! :)

**Pull request closed without merging**
